# Generated by Django 3.2.2 on 2021-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogproject',
            name='url',
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.TextField(),
        ),
    ]
