# Generated by Django 3.2.2 on 2021-06-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogproject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
